export const LESSON_REGISTER_REQUEST = "LESSON_REGISTER_REQUEST";
export const LESSON_REGISTER_SUCCESS = "LESSON_REGISTER_SUCCESS";
export const LESSON_REGISTER_FAIL = "LESSON_REGISTER_FAIL";

export const LESSON_DETAILS_REQUEST = "LESSON_DETAILS_REQUEST";
export const LESSON_DETAILS_SUCCESS = "LESSON_DETAILS_SUCCESS";
export const LESSON_DETAILS_FAIL = "LESSON_DETAILS_FAIL";
export const LESSON_DETAILS_RESET = "LESSON_DETAILS_RESET";

export const LESSON_DELETE_REQUEST = "LESSON_DELETE_REQUEST";
export const LESSON_DELETE_SUCCESS = "LESSON_DELETE_SUCCESS";
export const LESSON_DELETE_FAIL = "LESSON_DELETE_FAIL";

export const LESSON_DETAILS_REQUEST_BYID = "LESSON_DETAILS_REQUEST_BYID";
export const LESSON_DETAILS_SUCCESS_BYID = "LESSON_DETAILS_SUCCESS_BYID";
export const LESSON_DETAILS_FAIL_BYID = "LESSON_DETAILS_FAIL_BYID";
export const LESSON_DETAILS_RESET_BYID = "LESSON_DETAILS_RESET_BYID";

export const LESSON_UPDATE_REQUEST = "LESSON_UPDATE_REQUEST";
export const LESSON_UPDATE_SUCCESS = "LESSON_UPDATE_SUCCESS";
export const LESSON_UPDATE_FAIL = "LESSON_UPDATE_FAIL";
export const LESSON_UPDATE_RESET = "LESSON_UPDATE_RESET";
