export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const TEACHER_REGISTER_REQUEST = "TEACHER_REGISTER_REQUEST";
export const TEACHER_REGISTER_SUCCESS = "TEACHER_REGISTER_SUCCESS";
export const TEACHER_REGISTER_FAIL = "TEACHER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const TEACHER_DETAILS_REQUEST = "TEACHER_DETAILS_REQUEST";
export const TEACHER_DETAILS_SUCCESS = "TEACHER_DETAILS_SUCCESS";
export const TEACHER_DETAILS_FAIL = "TEACHER_DETAILS_FAIL";
export const TEACHER_DETAILS_RESET = "TEACHER_DETAILS_RESET";

export const TEACHER_DETAILS_REQUEST_BYID = "TEACHER_DETAILS_REQUEST_BYID";
export const TEACHER_DETAILS_SUCCESS_BYID = "TEACHER_DETAILS_SUCCESS_BYID";
export const TEACHER_DETAILS_FAIL_BYID = "TEACHER_DETAILS_FAIL_BYID";
export const TEACHER_DETAILS_RESET_BYID = "TEACHER_DETAILS_RESET_BYID";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_UPDATE_PASSWORD_REQUEST = "USER_UPDATE_PASSWORD_REQUEST";
export const USER_UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_PASSWORD_SUCCESS";
export const USER_UPDATE_PASSWORD_FAIL = "USER_UPDATE_PASSWORD_FAIL";
export const USER_UPDATE_PASSWORD_RESET = "USER_UPDATE_PASSWORD_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const TEACHER_DELETE_REQUEST = "TEACHER_DELETE_REQUEST";
export const TEACHER_DELETE_SUCCESS = "TEACHER_DELETE_SUCCESS";
export const TEACHER_DELETE_FAIL = "TEACHER_DELETE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const TEACHER_UPDATE_REQUEST = "TEACHER_UPDATE_REQUEST";
export const TEACHER_UPDATE_SUCCESS = "TEACHER_UPDATE_SUCCESS";
export const TEACHER_UPDATE_FAIL = "TEACHER_UPDATE_FAIL";
export const TEACHER_UPDATE_RESET = "TEACHER_UPDATE_RESET";

export const USER_FORGOTPASSWORD_REQUEST = "USER_FORGOTPASSWORD_REQUEST";
export const USER_FORGOTPASSWORD_SUCCESS = "USER_FORGOTPASSWORD_SUCCESS";
export const USER_FORGOTPASSWORD_FAIL = "USER_FORGOTPASSWORD_FAIL";
export const USER_FORGOTPASSWORD_RESET = "USER_FORGOTPASSWORD_RESET";

export const USER_PASSWORDRESET_REQUEST = "USER_PASSWORDRESET_REQUEST";
export const USER_PASSWORDRESET_SUCCESS = "USER_PASSWORDRESET_SUCCESS";
export const USER_PASSWORDRESET_FAIL = "USER_PASSWORDRESET_FAIL";
export const USER_PASSWORDRESET_RESET = "USER_PASSWORDRESET_RESET";
